- docker-compose.yml
Pushed to testnet this evening.
Leaving until tomorrow to pull into production.
> Adds variant generators, new IDs and miner updates.

- docker-compose.yml
Just a very slight tweak to the miner container.
> Tweak miner slightly.

- docker-compose.yml
Just a very minor software update today:
- Bumps miner to latest version from helium
- Ensures bluetooth disconnects before re-starting advertising.
> Software Update 2021.05.25.1

- docker-compose.yml
- moo.txt
A small bug fix that resolves an issue with too many SSIDs on apple devices.
> Software Update  2021.05.26.2

- docker-compose.yml
> Bump to latest GA

- docker-compose.yml
- moo.txt
Urgent update to miner in relation to chain halt:
- Bumps miner to latest version from helium
> Software Update 2021.05.29.0

- docker-compose.yml
This software update introduces the following:
- Adds extra information relating to miner sync status etc to Diagnostics Page
- Bumps miner to latest GA (05.29.1)
- Adds firmware version to diagnostics page.
> Software Update 2021.05.31.0

- docker-compose.yml
This software update introduces the following:
- Adds further information to the diagnostics page including blockchain height and sync percentage.
- Adds a link to download the diagnostics json file to send to support
- Fixes region plans for AS923-1, AS923-2 & AS923-3
- Adds region plan for AS923-4
> Software Update 2021.06.01.0

- docker-compose.yml
A very simple update, this resolves some minor issues with the diagnostic's container sync percentage.
> Software Update 2021.06.01.1

- docker-compose.yml
Another smallish software update
- Bumps helium miner to latest GA, should help resolve remaining sync issues.
- Tweaks config program slightly to ensure firmware shown is more up to date.
- Tweak RSSI for 915 Mhz Units.
> Software Update 2021.06.10.1

- docker-compose.yml
Just bumps the miner to the latest GA of the 12th.
> Software Update 2021.06.12.0

- docker-compose.yml
Bump miner to latest GA 061420210
> Software Update 2021.06.16.0

- README.md
- docker-compose.yml
Bump miner to latest GA 061820210
> Software Update 2021.06.18.0

- README.md
- docker-compose.yml
- Bump miner to latest GA 062520213
- Improves some documentation
> Software Update 2021.06.25.1

- docker-compose.yml
Another urgent Helium Miner Release.
> Software Update 2021.06.26.2

- README.md
@ryanteck Please confirm that the below is all correct.
> Adds more documentation.

- README.md
- docker-compose.yml
This pushes a variety of updates:
- updates to latest hm-config version
- updates to latest hm-diag version
- bumps miner to latest GA 063020210
> Software Update 2021.06.30.0

- docker-compose.yml
- Bump hm-diag to fix percentage display
- Bump miner to latest GA 070220210
> Software Update 2021.07.02.1

- docker-compose.yml
- Update to latest miner release to improve sync times
https://engineering.helium.com/2021/07/11/blockchain-release-snapshot-performance-update.html
> Software Update 2021.07.11.0

- docker-compose.yml
Bump to latest version of miner
Once testnet has update and looks stable this can be pulled in
> Software Update 2021.07.19.0_GA

- .github/workflows/push-to-prod.yml
- .github/workflows/push-to-testnet.yml
- docker-compose.yml
> Software update 2021.07.22.0

- README.md
- docker-compose.yml
Updates miner to latest GA
updates to latest packet forwarder with SPI bus check
updates some documentation
>  Software update 2021.07.30.0

- docker-compose.yml
> Bump to 2021.08.02.0 GA

- docker-compose.yml
Bump production to latest miner
> Software update 2021.08.02.1

- docker-compose.yml
Software Update 2021.08.05.0_GA
> Software Update 2021.08.05.0_GA

- docker-compose.yml
Bump to ~~2021.08.11.0_GA~~ 2021.08.11.2_GA miner
Can be merged once everything looks good on testnet
> Software Update 2021.08.11.2_GA

- docker-compose.yml
bring in latest packet forwarder for further testing on testnet (has already been tested on light-hotspot-software)
> update: bring in latest packet forwarder for testing

- docker-compose.yml
**Why**
Updates to fix upstream changes.
**How**
**References**
> Update diag, config, UPnP and miner

- docker-compose.yml
Bump to 2021.08.21.0_GA
**Why**
**How**
**References**
> Bump to 2021.08.21.0_GA

- docker-compose.yml
update versioning according to latest GA
**Why**
reflect current version number
**How**
**References**
> fix versioning

- docker-compose.yml
**Why**
**How**
**References**
> Bump version

- docker-compose.yml
See - https://github.com/NebraLtd/hm-diag/issues/112
> Expose JON RPC API port to other docker containers

- docker-compose.yml
**Why**
* Updates miner to GA 2021-08-24.1
* Brings in latest changes from hm-config refactoring
> Updates hm-config and hm-miner

- docker-compose.yml
Bump to 2021.08.24.4_GA
Can be merged once stable on testnet
**Why**
**How**
**References**
> Bump to 2021.08.24.4_GA

- docker-compose.yml
**Why**
**How**
**References**
> merge aarons hacks for the new config shizzles

- docker-compose.yml
**Why**
Latest miner release
**How**
Bump containers
**References**
> Bump to 2021.08.31.1_GA

- docker-compose.yml
Bump to 2021.09.03.0_GA
Bump packet forwarder
**Why**
**How**
**References**
> Bump to 2021.09.03.0_GA

- .github/workflows/push-to-prod.yml
- .github/workflows/push-to-testnet.yml
- docker-compose.yml
**Why**
Update to latest miner, config and diag
**How**
Bump miner, diag and config containers to latest versions.
**References**
https://engineering.helium.com/2021/09/14/major-blockchain-release-pocv11-support-snapshot-updates-performance-improvements.html
> Software Update 2021.09.14.0_GA

- docker-compose.yml
**Why**
Releases latest GA to prod.
**How**
Checked on dev and testnet hosts.
**References**
https://discord.com/channels/404106811252408320/730418759298318346/888458893657784390
> Release latest GA (2021-09-16)

- docker-compose.yml
Bump to pull in latest config file
**Why**
**How**
**References**
> Bump to pull in latest config file

- docker-compose.yml
Changelog:
* Brings in hm-pyhelper 
* Deprecates helium-hardware-definitions (in favor of hm-pyhelper)
* Improves logger in hm-config
* Adopts JSONRPC in hm-diag
> Updates a number of packages

- docker-compose.yml
**Why**
**How**
**References**
> Roll out hm-diag changes to testnet

- docker-compose.yml
**Why**
**How**
**References**
> Bump hm-diag for new diagnostics interval

- docker-compose.yml
Bump snapshot
**Why**
**How**
**References**
> Bump snapshot

- docker-compose.yml
Fix regression
**Why**
**How**
**References**
> Fix regression

- .github/workflows/push-to-prod.yml
- .github/workflows/push-to-testnet.yml
**Why**
**How**
**References**
> Merge production back to master

- .github/workflows/push-to-prod.yml
- .github/workflows/push-to-testnet.yml
- docker-compose.yml
**Why**
Fix key length check in gwmfr
**How**
Bump containers
**References**
https://github.com/NebraLtd/hm-gwmfr/issues/22
https://github.com/NebraLtd/hm-gwmfr/pull/23
> Fix key length check

- README.md
- docker-compose.yml
> Sunsets hm-gwmfr in favor of new feature in hm-diag

- docker-compose.yml
* Introduces implicit heath check for hm-diag (https://github.com/NebraLtd/hm-diag/pull/171)
* Introduces explicit health check for dbus container
> Adds healtchecks

- docker-compose.yml
**Why**
Update miner
**How**
Bump to 2021.10.29.0_GA
**References**
Supersedes: #187 
Requires: https://github.com/NebraLtd/hm-block-tracker/pull/36
> Bump to 2021.10.29.0_GA

- docker-compose.yml
**Why**
Bump to 2021.11.02.0_GA
**How**
Bump miner container
**References**
https://engineering.helium.com/2021/11/03/blockchain-release.html
> Bump to 2021.11.02.0_GA

- docker-compose.yml
**Why**
Keep up with GA releases.
**How**
Uses [new hm-miner by Mr. Bump](https://github.com/NebraLtd/hm-miner/commit/e348a6f4c45e01fef0e7a8e657c5eb4a673f4745).
**References**
Closes: https://github.com/NebraLtd/helium-miner-software/issues/193
> feat: bump GA to 2021.11.04.2

- .github/CODEOWNERS
**Why**
Partially fixes #208
**How**
Add tech support to CODEOWNERS
**References**
#208 
Will also need to do the same on production branch, perhaps in #212
> Add tech support to CODEOWNERS

- docker-compose.yml
**Why**
**How**
**References**
> Push 2021.11.16.3_GA

- .github/workflows/push-to-prod.yml
- .github/workflows/push-to-testnet.yml
- docker-compose.yml
**Why**
**How**
**References**
> Release 2021.11.16.3 to Production

- docker-compose.yml
**Why**
Bump to 2021.11.17.2 GA
**How**
Bump up latest GA in hm-miner
https://github.com/NebraLtd/hm-miner/commit/b34655ff2c59a0ad00546d3339321cab336bc030
**References**
Closes: #231 
Ref #230 #229 
https://engineering.helium.com/2021/11/17/blockchain-release-resuming-the-blockchain.html
> prod: Bump to 2021.11.17.2 GA

- docker-compose.yml
**Why**
Better handle exceptions in diagnostics
Better handle Bluetooth error messages in config
**How**
Test diag updates in https://github.com/NebraLtd/hm-diag/pull/212 and https://github.com/NebraLtd/hm-diag/pull/217
Test config updates in https://github.com/NebraLtd/hm-config/pull/129
**References**
https://github.com/NebraLtd/hm-diag/pull/212
https://github.com/NebraLtd/hm-diag/pull/217
https://github.com/NebraLtd/hm-diag/issues/204
https://github.com/NebraLtd/hm-config/pull/129
> Bump diagnostics and config

- .github/workflows/push-to-testnet.yml
- docker-compose.yml
**Why**
Get the latest changes into production.
**How**
Bump versions.
**References**
- Testnet release: https://github.com/NebraLtd/helium-miner-software/pull/237
- Closes: https://github.com/NebraLtd/hm-diag/issues/216
- Closes: https://github.com/NebraLtd/hm-config/issues/47
- Closes: https://github.com/NebraLtd/hm-diag/issues/223
- Related to: https://github.com/NebraLtd/hm-upnp/pull/7
- Partial fix for: https://github.com/NebraLtd/hm-config/issues/105
> release(prod): diagnostics errors fixed and config bluetooth improved

- docker-compose.yml
**Why**
Calls to Helium API were not going through because of missing header field
LOR should be a factor for PF
**How**
- Includes fix for API call to include headers
- Include LOR to be a factor for PF
**References**
[Helium API not returning due to missing headers](https://github.com/NebraLtd/hm-diag/pull/236)
[LOR should be a factor for PF](https://github.com/NebraLtd/hm-diag/pull/234)
> Bump diagnostics for new fixes

- docker-compose.yml
**Why**
Bump miner to latest GA
**How**
Update miner to latest GA 2021.11.19.0
**References**
https://github.com/NebraLtd/hm-miner/commit/0d4ce82e61a6d2fcb4a029c9d51b6de8c0443e48
> Update miner to latest GA 2021.11.19.0

- .github/workflows/push-to-prod.yml
- .github/workflows/push-to-testnet.yml
- docker-compose.yml
**Why**
Fix diverged master and production
Have done this from a separate branch to avoid a merge commit. This will then be resolved when pushing 2021.11.19.0 from master to production
**How**
Merge production back to master
**References**
#245 
Supersedes: #247 and #248
> Merge production to master

- docker-compose.yml
**Why**
**How**
**References**
> add i2c-7 for rockpi

- .github/workflows/update-miner.yml
- docker-compose.yml
**Why**
Update miner to latest GA 2021.11.21.1
**How**
Bump miner container and version numbers
**References**
https://github.com/NebraLtd/hm-miner/commit/31eeca0c7d85eeaa8bac799f943217f5f3541fbd
Closes: #255
> release(prod): Update miner to latest GA 2021.11.21.1

- .github/workflows/update-miner.yml
- docker-compose.yml
**Why**
Update miner to latest GA 2021.11.21.2
**How**
Bump to NebraLtd/hm-miner@2b505525140c5fec9b9f00c4703d3bdfca0ef396
**References**
Closes: #260
> release(prod): Update miner to latest GA 2021.11.21.2

- .github/workflows/update-miner.yml
- docker-compose.yml
**Why**
Pull in correct docker image
**How**
Due to new multi architecture building in hm-miner we need to now add the arm64 tag here
**References**
Requires: https://github.com/NebraLtd/hm-miner/pull/56
> fix: add arch type in name

- .github/workflows/update-production.yml
**Why**
fix environment variable
**How**
Change to correct ENV variable assignment
**References**
Fixes https://github.com/NebraLtd/helium-miner-software/commit/e62801a1aadd3733e80e81a0d00fe5c56499f9d4
> fix environment variable

- .github/workflows/update-production.yml
**Why**
**How**
**References**
> release(testnet): Update miner to latest GA 2021.11.22.0

- docker-compose.yml
**Why**
bump pktfwd to bring in sx1302 fixes
bump diag to bring in RockPi fixes
**How**
bump pktfwd to bring in sx1302 fixes
bump diag to bring in RockPi fixes
**References**
Brings in a subset of changes from #264 for testing
Relates-to: NebraLtd/hm-diag#237
Relates-to: NebraLtd/hm-pyhelper#68
Relates-to: NebraLtd/hm-pktfwd#74
Relates-to: NebraLtd/hm-pktfwd#72
Relates-to: NebraLtd/hm-pktfwd#70
> feat: bump packet forwarder and diag

- .github/workflows/update-production.yml
- docker-compose.yml
**Why**
Fix sx1302 and RockPi
**How**
Bump diag and packet forwarder
**References**
#264
#271 
Closes: NebraLtd/hm-diag#237
Relates-to: NebraLtd/hm-pyhelper#68
Relates-to: NebraLtd/hm-pktfwd#74
Relates-to: NebraLtd/hm-pktfwd#72
Closes: NebraLtd/hm-pktfwd#70
> Merge sx1302 and RockPi fixes to production

- docker-compose.yml
**Why**
This is a temporary fix to resolve the issue described in #281 so that @NebraLtd/tech-support can continue testing other recent changes
**How**
Make diag container privileged
**References**
#281
> fix: temporarily move diagnostics to privileged

- docker-compose.yml
**Why**
Fix rockpi ecc provisioning
**How**
Bump diagnostics container
**References**
Relates to https://github.com/NebraLtd/hm-diag/pull/260
> fix: bump diagnostics to fix rockpi provisioning

- .github/pull_request_template.md
**Why**
We are setting up a new PR template 
**How**
Applied new PR template to PR file
**References**
[Issue 23](https://github.com/NebraLtd/product-management/issues/23)
> New PR request template

- docker-compose.yml
**Issue**
- Link: https://github.com/NebraLtd/hm-config/issues/140
- Summary: enable flake8, bandit and fix up issues
**How**
Bump config container to latest hash https://github.com/NebraLtd/hm-config/commit/c6caddfe8cda4d00cd041c59ebd25a7b93cfdd5a
N/A
**References**
Closes: https://github.com/NebraLtd/hm-config/issues/140
**Checklist**
> feat: bump config container with flake8 fixes

- .github/workflows/push-to-prod-draft.yml
- .github/workflows/push-to-prod.yml
- .github/workflows/push-to-testnet-draft.yml
- README.md
- docker-compose.yml
**Issue**
- Link: #299 
- Summary: add random sleep period
**How**
Push fix to production 
**References**
#293 
**Checklist**
> release: fix balena pushes with random sleep period

- docker-compose.yml
**Issue**
- Link: https://github.com/NebraLtd/hm-config/pull/158
- Summary: add support for button and LED on ROCK Pi
**How**
Bump config container version to test RockPi button and LED support on testnet
N/A
**References**
Related to: Rockpi: Add GPIO support https://github.com/NebraLtd/hm-config/issues/96
Related to: Improve RockPi GPIO support https://github.com/NebraLtd/hm-config/issues/157
Related to: https://github.com/NebraLtd/hm-config/pull/158
**Checklist**
> feat: bump config hash for RockPi support

- .github/workflows/push-to-prod-draft.yml
- .github/workflows/push-to-prod.yml
- .github/workflows/push-to-testnet-draft.yml
- .github/workflows/push-to-testnet.yml
- README.md
- docker-compose.yml
**Issue**
- Link: https://github.com/NebraLtd/hm-config/pull/158
- Summary: add support for button and LED on ROCK Pi
**How**
Follow-up to testnet PR: https://github.com/NebraLtd/helium-miner-software/pull/302
N/A
**References**
- Closes: Rockpi: Add GPIO support https://github.com/NebraLtd/hm-config/issues/96
- Related to: Improve RockPi GPIO support https://github.com/NebraLtd/hm-config/issues/157
- Related to: https://github.com/NebraLtd/hm-config/pull/158
- Related to: https://github.com/NebraLtd/helium-miner-software/pull/301
- Related to: https://github.com/NebraLtd/helium-miner-software/pull/300
- 
**Checklist**
> release(prod): ROCK Pi improved build and GPIO support

- README.md
Add draft action link
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> fix: add draft action link to README

- README.md
**Issue**
- Link:
- Summary:
**How**
Add info about #301 and #299 to README
**References**
**Checklist**
> docs: add info about build workarounds

- docker-compose.yml
**Issue**
- Link: https://github.com/NebraLtd/packet_forwarder/pull/4
- Summary: pocv11 broke things
**How**
bump packet forwarder container
**References**
https://github.com/NebraLtd/packet_forwarder/pull/4
https://github.com/NebraLtd/hm-pktfwd/pull/77
**Checklist**
> fix: bump packet forwarder container

- docker-compose.yml
**Issue**
- Link: N/A
- Summary: pocv11 broke things
**How**
Bump packet forwarder
**References**
https://github.com/NebraLtd/hm-pktfwd/pull/77
https://github.com/NebraLtd/packet_forwarder/pull/4
**Checklist**
> hotfix: upstream helium fixes

- docker-compose.yml
**Issue**
- Link: https://github.com/NebraLtd/hm-diag/issues/273
- Summary: wget missing from diag
**How**
Add wget to diagnostics container to fix healthcheck
**References**
Relates to https://github.com/NebraLtd/hm-diag/issues/273
**Checklist**
> fix: fixes diagnostics healthcheck

- docker-compose.yml
**Issue**
- Link: https://github.com/NebraLtd/hm-config/issues/153
- Summary: add error message when no BT device
**How**
Bump config container
**References**
Relates to https://github.com/NebraLtd/hm-config/pull/160
Relates to https://github.com/NebraLtd/hm-config/issues/153
**Checklist**
> feat: add error message when no BT device

- docker-compose.yml
**Issue**
- Link: https://github.com/NebraLtd/helium-miner-software/pull/319
- Summary: bump diagnostics and config
**How**
**References**
Closes: https://github.com/NebraLtd/hm-diag/issues/273
Closes: https://github.com/NebraLtd/hm-config/issues/153
Ref https://github.com/NebraLtd/hm-diag/pull/274
Ref https://github.com/NebraLtd/hm-config/pull/160
Ref https://github.com/NebraLtd/helium-miner-software/pull/319
Ref https://github.com/NebraLtd/helium-miner-software/pull/320
**Checklist**
> release (prod): bump diagnostics and config

- docker-compose.yml
**Issue**
- Link: https://github.com/NebraLtd/hm-config/issues/162
- Summary: add firmware version to every container
**How**
**References**
Ref https://github.com/NebraLtd/hm-pyhelper/pull/84
Ref https://github.com/NebraLtd/hm-diag/pull/277
Closes: https://github.com/NebraLtd/hm-config/issues/162
**Checklist**
>  release (prod): bump diag and add firmware version to all containers

- docker-compose.yml
**Issue**
- Link: https://github.com/NebraLtd/hm-diag/issues/139
- Summary: add/fix sentry in all containers
**How**
Enable sentry in config, diag, pktfwd and UPnP and improve setup
**References**
Ref: https://github.com/NebraLtd/hm-upnp/pull/9
Ref: https://github.com/NebraLtd/hm-diag/pull/276
Ref: https://github.com/NebraLtd/hm-config/pull/163
Ref: https://github.com/NebraLtd/hm-pktfwd/pull/82
Ref: https://github.com/NebraLtd/hm-diag/issues/139
**Checklist**
> fix: enable sentry in all containers

- docker-compose.yml
**Issue**
- Link: https://github.com/NebraLtd/hm-diag/issues/139
- Summary: add/fix sentry in all containers
**How**
Update miner to latest GA 2021.12.29.2
Ref #327
Pushed to testnet at Fri Dec 31 01:28:03 UTC 2021
Also enables sentry in config, diag, pktfwd and UPnP and improve setup
**References**
Ref: https://github.com/NebraLtd/hm-upnp/pull/9
Ref: https://github.com/NebraLtd/hm-diag/pull/276
Ref: https://github.com/NebraLtd/hm-config/pull/163
Ref: https://github.com/NebraLtd/hm-pktfwd/pull/82
Ref: https://github.com/NebraLtd/hm-diag/issues/139
Ref #327 
Ref https://engineering.helium.com/2021/12/30/blockchain-release-snapshot-loading-and-storage-improvements.html
**Checklist**
> release(prod): Update miner to latest GA 2021.12.29.2

- docker-compose.yml
**Issue**
- Link: https://github.com/NebraLtd/hm-diag/pull/279
- Summary: copyright year not updated
**How**
Bump diag to update copyright date
Relates to: https://github.com/NebraLtd/hm-diag/pull/279
**References**
https://github.com/NebraLtd/hm-diag/pull/279
**Checklist**
> fix: bump diag to update copyright date

- docker-compose.yml
**Issue**
- Link: ref #331 
- Summary:
**How**
Bump diagnostics container
**References**
**Checklist**
> release(prod): bump diagnostics container

- .github/workflows/push-to-testnet-draft.yml
- .github/workflows/push-to-testnet.yml
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> fix: correct file path in workflows

- .github/workflows/push-to-testnet.yml
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> fix: ignore paths to stop recursive behaviour

- .github/workflows/push-to-prod.yml
**Issue**
- Link: N/A 
- Summary: accidentally included an unnecessary if statement
**How**
Remove conditional
**References**
#272 
#341 
**Checklist**
> fix: typo in workflow

- setup.cfg
> Increased max line length to 100 for flake8.

- .github/workflows/push-to-prod-draft.yml
- .github/workflows/push-to-prod.yml
**Issue**
- Link: N/A
- Summary: the PR #387 introduced an error in pushing to new rak production fleet with no frequency variants
**How**
Remove some rak options
**References**
**Checklist**
> fix: remove rak frequencies from matrix

- README.md
- how_to_add_new_hotspot.md
**Issue**
(NebraLtd/helium-miner-software#380)
- Summary:
We needed a guide for further new type of hotspots.
**Checklist**
> Introduced how_to_add_new_hotspot.md guide

- balena/balena.yml.controllino
- balena/balena.yml.cotx
- balena/balena.yml.finestra
- balena/balena.yml.linxdot
- balena/balena.yml.og
- balena/balena.yml.pisces
- balena/balena.yml.rak
- balena/balena.yml.sensecap
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> Create balena.yml.linxdot and fix support links

- .github/workflows/openfleet-file-update.yml
- .github/workflows/push-to-prod-draft.yml
- .github/workflows/push-to-prod.yml
- .github/workflows/push-to-testnet-draft.yml
- .github/workflows/push-to-testnet.yml
- balena/balena.yml.pantherx1
- balena/balena.yml.pycom
- balena/balena.yml.risinghf
- balena/balena.yml.syncrobit
**Issue**
- Link: N/A
- Summary: feat: create balena.yml files and update workflows
**How**
- create balena.yml for pantherx1, syncrobit, pycom, risinghf
- update linxdot and controllino / conelcom balena.yml
- update repo update workflow  to include all third party tracker repos for balenaHub / OpenFleets
- update deploy workflows to include new third party fleets on balena
**References**
https://github.com/NebraLtd/helium-controllino/issues/3
**Checklist**
> feat: create balena.yml files and update workflows

- .github/workflows/push-to-prod-draft.yml
- .github/workflows/push-to-prod.yml
**Issue**
- Link: N/A
- Summary: trigger auto image build for open fleets
**How**
trigger auto image build for open fleets via repository dispatch action which is picked up by actions in the other repos such as https://github.com/NebraLtd/helium-rak/commit/ab3edd0cb3076a99d65758548354f90765acff25
**References**
https://github.com/NebraLtd/helium-rak/commit/ab3edd0cb3076a99d65758548354f90765acff25
**Checklist**
> feat: trigger auto image build for open fleets

- README.md
Closes: #545
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> docs: add documentation for OpenFleets

- .github/workflows/openfleet-file-update.yml
- .github/workflows/push-to-prod-draft.yml
- .github/workflows/push-to-prod.yml
- .github/workflows/update-miner.yml
- .github/workflows/update-production.yml
Bump versions
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> fix: bump action versions

- .github/workflows/push-to-prod-draft.yml
- .github/workflows/push-to-prod.yml
- balena/balena.yml.raspi-indoor
- balena/balena.yml.raspi-outdoor
- balena/balena.yml.rockpi-indoor
- balena/balena.yml.rockpi-outdoor
Add in balena.yml files to deploy
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> feat: add in balena.yml to deploy

- .github/workflows/push-to-prod-draft.yml
- .github/workflows/push-to-prod.yml
- .github/workflows/push-to-testnet-draft.yml
- .github/workflows/push-to-testnet.yml
- balena/workflows/build-open-fleet.yml
- balena/workflows/update-files.yml
**Issue**
- Link:
- Summary: balena deploy to new commercial fleets
**How**
- update push-to-prod-draft.yml and push-to-prod.yml to push to commercial fleets
- update build-open-fleets.yml and update-files.yml files
- bump balena cli version in actions
**References**
**Checklist**
> feat: balena deploy to new commercial fleets

- .github/workflows/push-to-prod-draft.yml
- .github/workflows/push-to-prod.yml
- .github/workflows/push-to-testnet-draft.yml
- .github/workflows/push-to-testnet.yml
- balena/balena.yml.raspi-indoor
- balena/balena.yml.raspi-outdoor
- balena/balena.yml.rockpi-indoor
- balena/balena.yml.rockpi-outdoor
- balena/workflows/build-open-fleet.yml
- balena/workflows/update-files.yml
- device-compose-files/docker-compose-pisces.yml
- device-compose-files/docker-compose-pycom.yml
- device-compose-files/docker-compose-rockpi.yml
- device-compose-files/docker-compose-rpi.yml
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> release (prod): add new commercial fleets

- .github/workflows/push-to-prod-draft.yml
- .github/workflows/push-to-prod.yml
missing fleets
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> fix: missing fleets

- .github/workflows/push-to-prod-draft.yml
- .github/workflows/push-to-prod.yml
- device-compose-files/docker-compose-pisces.yml
- device-compose-files/docker-compose-pycom.yml
- device-compose-files/docker-compose-rockpi.yml
- device-compose-files/docker-compose-rpi.yml
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> release (prod): fix missing fleets

- device-compose-files/docker-compose-pycom.yml
- device-compose-files/docker-compose-rockpi.yml
- device-compose-files/docker-compose-rpi.yml
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> release (prod): fleet reduction

- .github/workflows/push-to-prod-draft.yml
- .github/workflows/push-to-prod.yml
- device-compose-files/docker-compose-pisces.yml
- device-compose-files/docker-compose-pycom.yml
- device-compose-files/docker-compose-rockpi.yml
- device-compose-files/docker-compose-rpi.yml
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> release (prod): split

- balena/workflows/build-open-fleet.yml
Add random sleep and multiple API keys to build action to fix issues with Balena API getting overloaded
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> feat: add random sleep to build

- balena/workflows/build-open-fleet.yml
**Issue**
- Link:
- Summary:
**How**
bump balena base images to latest 2023.1.0 ESR releases
**References**
**Checklist**
> feat: bump balena base images

- gen_docker_compose.py
this repo already uses jinja2 so remove comments saying this would be in the future.
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> docs: update comment mentioning jinja2 as future

- .github/workflows/python-tests.yml
Fix pytest cov
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> fix: pytest cov not working correctly

- .github/workflows/push-to-prod-draft.yml
- .github/workflows/push-to-prod.yml
- .github/workflows/push-to-testnet-draft.yml
- .github/workflows/push-to-testnet.yml
**Issue**
- Link: #594 
- Summary: move commercial actions to separate repo
**How**
move commercial actions to separate repo
**References**
https://github.com/NebraLtd/commercial-hotspot-software
https://github.com/NebraLtd/commercial-hotspot-software/issues/2
Follow up issues...
https://github.com/NebraLtd/commercial-hotspot-software/issues/6
https://github.com/NebraLtd/commercial-hotspot-software/issues/5
**Checklist**
> feat: move commercial actions to separate repo

- tests/test_output.py
Add pisces and Pycom to test cases
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> fix: add Pycom and pisces to test cases

- tests/test_output.py
forgot to add to cleanup
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> bug: cleanup properly

- .github/workflows/push-to-prod-draft.yml
- .github/workflows/push-to-prod.yml
Exclude some non existent repos
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> fix: repair conditional for other repos

- templates/docker-compose.template
Relates-to: https://github.com/NebraLtd/hm-pktfwd/issues/123
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> feat: add nebra volume to packet forwarder

- device-compose-files/docker-compose-pisces.yml
- device-compose-files/docker-compose-pycom.yml
- device-compose-files/docker-compose-rockpi.yml
- device-compose-files/docker-compose-rpi.yml
- templates/docker-compose.template
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> release(prod): fix pktfwd volumes

- .github/workflows/push-to-prod-nebraos-cloud-draft.yml
- .github/workflows/push-to-prod-nebraos-cloud-freq.yml
- .github/workflows/push-to-prod-nebraos-cloud.yml
- .github/workflows/push-to-testnet-nebraos-cloud-draft.yml
- .github/workflows/push-to-testnet-nebraos-cloud.yml
As I've renamed admin org to NebraLtd, I've adapted the CI, too.
**Checklist**
> Changed NebraOS org slug from admin to nebraltd

- templates/docker-compose.template
* set diag to restart always.
**[Issue](https://github.com/NebraLtd/helium-miner-software/issues/649)**
- Link:https://github.com/NebraLtd/helium-miner-software/issues/649
- Summary:
**How**
**References**
**Checklist**
> fix: mark container for auto restart #649

- .github/workflows/push-to-prod-old-fleets-nebraos-cloud.yml
- .github/workflows/push-to-testnet-old-fleets-nebraos-cloud.yml
* use v15.0.3-1 of balena-cli container for nebra cloud deploy
**[Issue](https://github.com/NebraLtd/NebraOS/issues/25)**
- Link: https://github.com/NebraLtd/NebraOS/issues/25
- Summary:
**How**
**References**
**Checklist**
> feat:  push to old fleets on nebra os cloud #25

- balena/workflows/balena-app.yml
- balena/workflows/update-files.yml
build balena apps from openfleet repos
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> feat: add balena-app.yml action

- balena/ssh/ssh_public_keys.json
- balena/workflows/build-open-fleet.yml
- balena/workflows/update-files.yml
update build open fleets production
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> feat: update build open fleets

- .github/workflows/push-to-prod-old-fleets-nebraos-cloud-draft.yml
- .github/workflows/push-to-prod-old-fleets-nebraos-cloud.yml
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> fix: syntax error

- .github/workflows/push-to-prod-old-fleets-nebraos-cloud-draft.yml
- .github/workflows/push-to-prod-old-fleets-nebraos-cloud.yml
- .github/workflows/push-to-testnet-old-fleets-nebraos-cloud-draft.yml
- .github/workflows/push-to-testnet-old-fleets-nebraos-cloud.yml
Don't try to trigger build action in archived repos
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> fix: don't trigger action in archived repos

- balena/workflows/balena-app.yml
- balena/workflows/build-open-fleet.yml
Old repo names in build action for RockPi
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> fix: wrong repo names

- .github/workflows/commercial-file-update.yml
- .github/workflows/openfleet-file-update.yml
- .github/workflows/push-to-prod-old-fleets-nebraos-cloud-draft.yml
- .github/workflows/push-to-prod-old-fleets-nebraos-cloud.yml
- .github/workflows/push-to-testnet-old-fleets-nebraos-cloud-draft.yml
- .github/workflows/push-to-testnet-old-fleets-nebraos-cloud.yml
- balena/workflows/balena-app.yml
- balena/workflows/build-open-fleet.yml
* fix: don't trigger action in archived repos 
Don't try to trigger build action in archived repos
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> fix: don't trigger action in archived repos (#690)

- templates/docker-compose.template
feat: add version variable so container is properly restarted
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> feat: add version variable so container is properly restarted

- .github/workflows/update-production.yml
release(testnet): Update Gatewayrs to latest GA v1.0.2
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> release(testnet): Update Gatewayrs to latest GA v1.0.2

- balena/workflows/build-open-fleet.yml
Rkcm3 fleets are RockPi
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> fix: rkcm3 fleets are RockPi

- .github/workflows/push-to-prod-new-fleets-nebraos-cloud-draft.yml
- .github/workflows/push-to-prod-new-fleets-nebraos-cloud.yml
- .github/workflows/push-to-prod-old-fleets-nebraos-cloud-draft.yml
- .github/workflows/push-to-prod-old-fleets-nebraos-cloud.yml
- .github/workflows/push-to-testnet-nebraos-cloud-draft.yml
- .github/workflows/push-to-testnet-nebraos-cloud.yml
- balena/workflows/build-open-fleet.yml
**Issue**
- Link:
- Summary:
**How**
- only Balena deploy when certain files are changed
- bump balena cli version
- add workflow_dispatch so we can manually push if necessary
**References**
**Checklist**
> fix: only Balena deploy when certain files are changed

- .github/workflows/push-to-prod-new-fleets-nebraos-cloud.yml
- .github/workflows/push-to-prod-old-fleets-nebraos-cloud.yml
wrong branch
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> fix: wrong branch

- .github/workflows/push-to-prod-new-fleets-nebraos-cloud.yml
- .github/workflows/push-to-prod-old-fleets-nebraos-cloud.yml
* fix: wrong branch
wrong branch
* Update push-to-prod-old-fleets-nebraos-cloud.yml
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> fix: wrong branch (#739)

- requirements.txt
- test-requirements.txt
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> Bump pyhelper

- README.md
- balena/workflows/update-action-test.yml
- balena/workflows/update-files.yml
* feat: add sample automation actions for OpenFleet repos
- add sample automation actions for OpenFleet repos - test and production versions
- add sample automation actions to OpenFleet repo update-files.yml so any updates get pulled through to the repo
- update readme to reflect removal of UPnP from hm-config container
- add weekly cron just in case missed update...on rare occasions the report dispatch gets fired before the main repo update is complete. This means the daughter repo never gets updated until the next repository dispatch action. This adds a weekly cron for a belt and braces approach.
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> feat: add sample automation actions for OpenFleet repos (#685)

- balena/workflows/update-files.yml
create directories if they dont exist
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> fix: create directories if they dont exist

- .github/workflows/push-to-prod-nebraos-cloud.yml
- .github/workflows/push-to-testnet-nebraos-cloud.yml
fix: workflow dispatch over-indented
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> fix: workflow dispatch over-indented

- .github/workflows/push-to-prod-nebraos-cloud-draft.yml
- .github/workflows/push-to-prod-nebraos-cloud.yml
- .github/workflows/push-to-testnet-nebraos-cloud-draft.yml
- .github/workflows/push-to-testnet-nebraos-cloud.yml
- balena/workflows/balena-app.yml
- balena/workflows/build-open-fleet.yml
- balena/workflows/update-action-prod.yml
- balena/workflows/update-action-test.yml
bump
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> bump versions

- .github/workflows/push-to-prod-nebraos-cloud-draft.yml
- .github/workflows/push-to-prod-nebraos-cloud.yml
- .github/workflows/push-to-testnet-nebraos-cloud-draft.yml
- .github/workflows/push-to-testnet-nebraos-cloud.yml
- balena/workflows/balena-app.yml
- balena/workflows/build-open-fleet.yml
- balena/workflows/update-action-prod.yml
- balena/workflows/update-action-test.yml
* bump versions
bump
* Update balena-app.yml
* Update update-action-prod.yml
* Update update-action-test.yml
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> bump versions (#760)

- balena/balena.yml.controllino
- balena/balena.yml.cotx
- balena/balena.yml.finestra
- balena/balena.yml.linxdot
- balena/balena.yml.linxdot-rkcm3
- balena/balena.yml.midas
- balena/balena.yml.nebra-indoor1
- balena/balena.yml.nebra-indoor2
- balena/balena.yml.nebra-outdoor1
- balena/balena.yml.nebra-outdoor2
- balena/balena.yml.og
- balena/balena.yml.pantherx1
- balena/balena.yml.pisces
- balena/balena.yml.pycom
- balena/balena.yml.rak
- balena/balena.yml.risinghf
- balena/balena.yml.sensecap
- balena/balena.yml.syncrobit
- balena/balena.yml.syncrobit-rkcm3
update balena.ymls to remove unneeded parts
- no longer need HELIUM_MINER_HEIGHT_URL on any miners
- no longer need vc4-kms-v3d on nebra miners
- match balena.yml files to relevant config.txt files
Related to #303 
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> feat: update balena.ymls to remove unneeded parts

- .github/workflows/commercial-file-update.yml
- .github/workflows/commercial-settings-update.yml
- .github/workflows/push-to-prod-nebraos-cloud-draft.yml
- .github/workflows/push-to-prod-nebraos-cloud.yml
- .github/workflows/push-to-testnet-nebraos-cloud-draft.yml
- .github/workflows/push-to-testnet-nebraos-cloud.yml
- balena/workflows/balena-app.yml
- balena/workflows/build-open-fleet.yml
- balena/workflows/update-action-prod.yml
- balena/workflows/update-action-test.yml
Bump balenaOS and cli versions
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> balena: bump OS and cli versions

- .github/workflows/commercial-file-update.yml
- .github/workflows/commercial-settings-update.yml
Send branch as payload
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> Send branch as payload

- .github/workflows/commercial-file-update.yml
- .github/workflows/commercial-settings-update.yml
* Send branch as payload
Send branch as payload
* Update commercial-settings-update.yml
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> Send branch as payload (#790)

- .github/workflows/push-to-prod-nebraos-cloud-draft.yml
- .github/workflows/push-to-prod-nebraos-cloud.yml
- .github/workflows/push-to-testnet-nebraos-cloud-draft.yml
- .github/workflows/push-to-testnet-nebraos-cloud.yml
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> Reduce concurrency

- balena/workflows/build-open-fleet.yml
Explicitly define Python version in OpenFleet image build
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> Explicitly define Python version in OpenFleet image build

- requirements.txt
- tests/test_output_by_variant.py
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> Add compose file test for Bobcat PX30

- .github/workflows/build-open-fleets.yml
- .github/workflows/openfleet-file-update.yml
- .github/workflows/push-to-prod-nebraos-cloud-draft.yml
- .github/workflows/push-to-prod-nebraos-cloud.yml
- .github/workflows/push-to-testnet-nebraos-cloud-draft.yml
- .github/workflows/push-to-testnet-nebraos-cloud.yml
- balena/workflows/build-open-fleet.yml
- balena/workflows/update-files.yml
add bobcat-px30
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> add bobcat to workflows

- .github/workflows/openfleet-file-update.yml
only update files with pushes to master or prod
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> only update files with pushes to master or prod

- balena/workflows/build-open-fleet.yml
Add Bobcat name to action
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> Clarify name

- .github/workflows/push-to-prod-nebraos-cloud-draft.yml
- .github/workflows/push-to-prod-nebraos-cloud.yml
- .github/workflows/push-to-testnet-nebraos-cloud-draft.yml
- .github/workflows/push-to-testnet-nebraos-cloud.yml
- balena/workflows/balena-app.yml
- balena/workflows/build-open-fleet.yml
- balena/workflows/update-action-prod.yml
- balena/workflows/update-action-test.yml
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> Bump OS versions

- balena/workflows/build-open-fleet.yml
Related to https://github.com/NebraLtd/helium-bobcat-px30/pull/9
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> bump bobcat version

- .github/workflows/push-to-prod-nebraos-cloud-draft.yml
- .github/workflows/push-to-prod-nebraos-cloud.yml
- .github/workflows/push-to-testnet-nebraos-cloud-draft.yml
- .github/workflows/push-to-testnet-nebraos-cloud.yml
- balena/workflows/balena-app.yml
- balena/workflows/build-open-fleet.yml
- balena/workflows/update-action-prod.yml
- balena/workflows/update-action-test.yml
* bump versions
* Update balena-app.yml
* Update update-action-prod.yml
* Update update-action-test.yml
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> bump versions (#848)

- balena/balena.yml.sensecap
- balena/config/config.txt.sensecap
- balena/config/config.txt.syncrobit
- balena/workflows/update-files.yml
Closes: https://github.com/NebraLtd/hm-pyhelper/issues/116
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> Sensecap fan support

- balena/balena.yml.sensecap
- balena/config/config.txt.sensecap
- balena/config/config.txt.syncrobit
- balena/workflows/update-files.yml
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> Merge to prod

- .github/workflows/push-to-prod-nebraos-cloud-draft.yml
- .github/workflows/push-to-prod-nebraos-cloud.yml
- .github/workflows/push-to-testnet-nebraos-cloud-draft.yml
- .github/workflows/push-to-testnet-nebraos-cloud.yml
- balena/workflows/balena-app.yml
- balena/workflows/build-open-fleet.yml
- balena/workflows/update-action-prod.yml
- balena/workflows/update-action-test.yml
* Update build-open-fleet.yml
* Update balena-app.yml
* Update update-action-prod.yml
* Update update-action-test.yml
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> Update build-open-fleet.yml (#856)

- .github/workflows/build-open-fleets.yml
- .github/workflows/openfleet-file-update.yml
- .github/workflows/push-to-prod-nebraos-cloud-draft.yml
- .github/workflows/push-to-prod-nebraos-cloud.yml
- .github/workflows/push-to-testnet-nebraos-cloud-draft.yml
- .github/workflows/push-to-testnet-nebraos-cloud.yml
- balena/balena.yml.bobcat-rk3566
- balena/workflows/build-open-fleet.yml
- balena/workflows/update-files.yml
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> bobcat rk3566

- .github/workflows/build-open-fleets.yml
- .github/workflows/openfleet-file-update.yml
- .github/workflows/push-to-prod-nebraos-cloud-draft.yml
- .github/workflows/push-to-prod-nebraos-cloud.yml
- .github/workflows/push-to-testnet-nebraos-cloud-draft.yml
- .github/workflows/push-to-testnet-nebraos-cloud.yml
- balena/balena.yml.bobcat-rk3566
- balena/workflows/build-open-fleet.yml
- balena/workflows/update-files.yml
* bobcat rk3566
* Update build-open-fleet.yml
* Update update-files.yml
* Update build-open-fleets.yml
* Update openfleet-file-update.yml
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> bobcat rk3566 (#859)

- .github/workflows/openfleet-file-update.yml
- .github/workflows/push-to-prod-nebraos-cloud-draft.yml
- .github/workflows/push-to-prod-nebraos-cloud.yml
- .github/workflows/push-to-testnet-nebraos-cloud-draft.yml
- .github/workflows/push-to-testnet-nebraos-cloud.yml
- balena/balena.yml.linxdot-rk3566
- balena/workflows/balena-app.yml
- balena/workflows/build-open-fleet.yml
- balena/workflows/update-action-prod.yml
- balena/workflows/update-action-test.yml
- balena/workflows/update-files.yml
- requirements.txt
- test-requirements.txt
* Update balena.yml.linxdot-rkcm3
* Update and rename balena.yml.linxdot-rkcm3 to balena.yml.linxdot-rk3566
* Update requirements.txt
* Update test-requirements.txt
* Update openfleet-file-update.yml
* Update build-open-fleet.yml
* Update balena-app.yml
* Update update-action-prod.yml
* Update update-action-test.yml
* Update balena.yml.linxdot-rk3566
* Update update-files.yml
**Issue**
- Link:
- Summary:
**How** …
> Update balena.yml.linxdot-rkcm3 (#881)
