- docker-compose.yml
This software update will do the following:
- Updates the helium miner to the latest version.
- Fixes an issue where the variant names were not showing correctly in the app
- Fixes diagnostics system in BT app
- Does some other improvements to the configuration file handling code.
> Software Update 2021.05.21.2

- docker-compose.yml
This software update will do the following:
- Updates the helium miner to the latest version.
- Fixes an issue where diagnostics app was not showing the correct IP address
- Fixes an issue with the Diagnostics web page not formatting correctly on mobile.
- Adds in improved way to show new firmware versions by passing argument from config.
> Software Update 2021.05.24.2

- docker-compose.yml
A minor follow up from https://github.com/NebraLtd/helium-miner-software/pull/47
Finishes implementation of Wi-Fi remove function to make it forget the wi-fi network.
Tweaks button handling responsiveness.
> Software Update 2021.05.24.4

- docker-compose.yml
Just a minor software update that resolves the following:
- Diagnostics runs now every minute instead of every 5, making information more up to date.
- Tweaked time on diagnostics to show timezone (UTC)
- Tweaked diagnostics date to be more regionally friendly
- Attempt to show if the miner is relayed (if programmed in correctly)
- Tweaks some logic to fix div by 0 error
- Bumps NGINX version
> Software Update 2021.06.03.0

- docker-compose.yml
A few changes in this software update:
- Diagnostics now displays more user friendly information when values aren't available
- Diagnostics now colour codes weather it is relayed or not
- Temporarily disable error reporting on diagnostics software to stop issues with sentry
- Bumps helium miner to latest GA.
- Tweaks RSSI value to try and improve witnesssing on 868 Mhz units (EU868, IN865, RU864)
> Software Update 2021.06.09.4

- docker-compose.yml
Need to wait until TestNet has stabilized.
There are no really important changes in this PR. The primary objective is to force miner container restarts, such that they will pull down the latest `docker.config`.
> Merges new changes into production

- docker-compose.yml
remove the inverted commas around public keys variable to fix the broken diagnostics container in https://github.com/NebraLtd/hm-diag/issues/75
> diag: fix issue with diagnostics container

- docker-compose.yml
- Bump hm-miner to fix public key variable issue in diagnostics
- Bump miner to latest GA 070920212
> Software Update 2021.07.09.2

- docker-compose.yml
Helium have changed the GA format again to 2021_09.26.0 instead of what it was typically before 2021.09.26.0 so hopefully this doesn't break anything with regards to the sys.config location (need to test thoroughly)
**Why**
**How**
**References**
> Bump miner to 2021_09.26.0

- docker-compose.yml
**Why**
Some ECC chips are being corrupted during manufacturing. There may be a race condition between gwmfr and diag. We want to wait for gwmfr to complete before running diagnostics.
**How**
Write to an empty file (AKA touch) when gwmfr completes successfully. Wait for this file to be present before running diagnostics.
**References**
- Slack convo: https://pisupply.slack.com/archives/C024BNQ1Y6T/p1632912403459500
- gwmfr: https://github.com/NebraLtd/hm-gwmfr/pull/18
- hm-diag: https://github.com/NebraLtd/hm-diag/pull/164
> feat: start diag after gwmfr writes ECC

- docker-compose.yml
Why
Was getting an error when trying to touch a file with pathlib, ModuleNotFoundError: No module named 'pathlib'. Because pathlib is not included in python3-minimal.
How
Use open().
References
Fixes: #18
New method: https://stackoverflow.com/questions/12654772/create-empty-file-using-python/12654798
Old method: https://stackoverflow.com/questions/1158076/implement-touch-using-python
gwmfr: https://github.com/NebraLtd/hm-gwmfr/pull/19
> fix: gwmfr uses correct touch method

- .github/workflows/push-to-prod.yml
- docker-compose.yml
**Why**
- enable usage of devices without com.helium.Miner.conf file (e.g. rockpi)
- change to dbus container setup
- pull in fixes to miner/diag/config containers to suit the above
- fix formatting of docker-compose.yml
- add new consolidation balena fleets to deploy workflow
**How**
Bump containers and update workflow
**References**
Closes: #105
> change to dbus container and pull in fixes

- docker-compose.yml
**Why**
We believe PoC v11 introduced weird behavior with regions:
https://nebraltd.slack.com/archives/C01RBDAEW56/p1636541564093200
**How**
Production is currently behind pktfwd master. This change points to a
pktfwd branch that forks from the current production commit: a901153
**References**
Relates to: https://github.com/NebraLtd/hm-pktfwd/issues/68
Relevant pktfwd branch: https://github.com/NebraLtd/hm-pktfwd/tree/marvinmarnold/hotfix%2Fregion-format
> hotfix: support new region format

- docker-compose.yml
**Why**
Keep up with GA releases.
**How**
Uses [new hm-miner by Mr. Bump](https://github.com/NebraLtd/hm-miner/commit/6ee720d968173f50c92a67f538bc69837dd61b9f).
**References**
Related to: https://github.com/NebraLtd/helium-miner-software/issues/203
> release(testnet): GA 2021.11.10.0

- docker-compose.yml
**Why**
Keep up with GA releases.
**How**
Uses [new hm-miner by Mr. Bump](https://github.com/NebraLtd/hm-miner/commit/4e4d5cc0b0f0d1b7d0a5250e5bdff8bc3dba6361).
**References**
- Related to: https://github.com/NebraLtd/helium-miner-software/issues/210
- Supercedes: https://github.com/NebraLtd/helium-miner-software/pull/205
> release(testnet): GA 2021.11.11.0

- docker-compose.yml
This is an urgent release and will be pushed ASAP once #211 has been vetted in testnet.  Released to testnet on 12 Nov 21 at 03:00 UTC .
**Why**
Master branch is not stable so applying GA directly.
**How**
Bump to hm-miner to commit https://github.com/NebraLtd/hm-miner/commit/6ee720d968173f50c92a67f538bc69837dd61b9f and update `FIRMWARE_VERSION`s.
**References**
- Related to: https://github.com/NebraLtd/helium-miner-software/pull/211
- Closes: https://github.com/NebraLtd/helium-miner-software/issues/210
- Potentially closes: https://github.com/NebraLtd/helium-miner-software/issues/203 & https://github.com/NebraLtd/helium-miner-software/pull/207
- Potentially closes: https://github.com/NebraLtd/helium-miner-software/pull/196
> release(prod): GA 2021.11.11.0

- docker-compose.yml
Going to do some testing before converting from draft.
**Why**
Manufacturing has slowed for a number of reasons. This PR addresses ECC locking and the initFile intentionally throwing 500s. 
**How**
Lock ECC usage and ensure initFile always returns something.
**References**
- Closes: https://github.com/NebraLtd/hm-diag/issues/167
- Includes: https://github.com/NebraLtd/hm-diag/issues/198
- Includes: https://github.com/NebraLtd/hm-pyhelper/issues/59
- Includes: https://github.com/NebraLtd/hm-diag/issues/181
Additional work still needed:
- https://github.com/NebraLtd/hm-diag/issues/204
- https://github.com/NebraLtd/Hotspot-Production-Tool/issues/32
- https://github.com/NebraLtd/Hotspot-Production-Tool/issues/33
> fix: ECC locking and initFile

- README.md
- docker-compose.yml
**Why**
`master` and `production` have diverged. This will put them back in parity. **Warning, because of the drift, this PR requires extra attention before merging.**
**How**
Because the branches have diverged, `master` cannot be directly merged into production. This PR solves merge conflicts. It will need to be merged into `production` and back-merged into `master`. `-1` also appended to `FIRMWARE_VERSION` to indicate that it is distinct Nebra release using the same Helium version.
**References**
- Testnet notes and changelog: https://github.com/NebraLtd/helium-miner-software/pull/209
- Includes: https://github.com/NebraLtd/hm-pktfwd/pull/59
> release(prod): 2021.11.11.0-1, ECC concurrency, initFile robustness, and pktfwd rewrite

- docker-compose.yml
Fix for issue #223
**Why**
Bump diag container version to fix #223
**How**
Bump diag container to version NebraLtd/hm-diag@b1210ec
**References**
Closes: [#223](https://github.com/NebraLtd/hm-diag/issues/223)
> Bump diagnostics to handle helium api errors

- docker-compose.yml
**Why**
Support rockpi with custom docker.config file to enable i2c bus i2c-7
**How**
Bumps miner container to 8cec30b in order to:
- add RockPi config file override to start-miner.sh
- add docker.config.rockpi template and use as default for rockpi
- update dockerfile to copy new template
- update README
- bump packet forwarder to latest version
**References**
Relates-to: NebraLtd/hm-miner#53
Relates-to: NebraLtd/hm-miner#31
Relates-to: NebraLtd/hm-block-tracker#52
Supersedes: #239
> feat: add rockpi support to miner

- dbus/Dockerfile
- docker-compose.yml
**Why**
In an attempt to force the container to recover, make a trivial change to the container.
**How**
Add a touchfile to the dbus-session container.
**References**
- Related to: https://github.com/NebraLtd/product-management/issues/28
> feat: rebuild dbus container with touchfile

- docker-compose.yml
**Why**
Bump to 2021.11.19.0 GA
**How**
Bump up latest GA in hm-miner
https://github.com/NebraLtd/hm-miner/commit/0d4ce82e61a6d2fcb4a029c9d51b6de8c0443e48
**References**
Ref #246
Closes: #251 
https://engineering.helium.com/2021/11/19/blockchain-release-sync-and-snapshot-improvements.html
> release(prod): bump miner to 2021.11.19.0 GA

- docker-compose.yml
**Why**
Update miner to latest GA 2021.11.21.1
**How**
Bump miner container and version numbers
**References**
https://github.com/NebraLtd/hm-miner/commit/31eeca0c7d85eeaa8bac799f943217f5f3541fbd
Relates-to: #255
> release(testnet): Update miner to latest GA 2021.11.21.1

- docker-compose.yml
**Why**
As per #253 adding /dev/i2c-7 works to enable the i2c on RockPi but stops the diagnostics and miner containers from starting on Raspberry Pi based devices as they have no i2c-7
**How**
This moves to privileged: true which should give access to all available buses
**References**
#253
> feat: support all i2c buses regardless of device

- .github/workflows/update-miner.yml
- .github/workflows/update-production.yml
- docker-compose.yml
Update miner to latest GA 2021.11.22.0
Ref #268
Pushed to testnet at Tue Nov 23 06:15:44 UTC 2021
> release(prod): Update miner to latest GA 2021.11.22.0

- docker-compose.yml
Added env var DIAGNOSTICS_VERSION to hold hm-diag git hash and updated hm-diag git hash to point to a commit that contains operational /version endpoint
**Why**
To allow the new `/version` endpoint in hm-diag to work.
**How**
Added DIAGNOSTICS_VERSION environment variable in docker-compose.yml that points to current hm-diag git hash. This is ready by the view for `/version` in hm-diag and returned as a json response.
> Version bump for hm-diag and inclusion of DIAGNOSTICS_VERSION

- docker-compose.yml
**Why**
Detect the BLE and LET devices in better way.
**How**
To get the BLE devices and LTE devices programatically using dbus, enable the dbus feature in `diagnostics` container.
**References**
https://github.com/NebraLtd/hm-diag/issues/96
https://github.com/NebraLtd/hm-diag/issues/88
https://github.com/NebraLtd/hm-config/issues/46
https://github.com/NebraLtd/hm-config/pull/152
https://github.com/NebraLtd/hm-config/pull/142
https://github.com/NebraLtd/hm-config/pull/141
> feat(diagnostics): better detect BT devices and LTE devices

- docker-compose.yml
**Why**
As a hotspot owner, I want to be able to access the serial-number.
**How**
Added label `io.balena.features.procfs` to diagnostics.
**References**
- Builds off: https://github.com/NebraLtd/hm-diag/pull/219
> fix(diagnostics): expose serial-number

- .github/workflows/push-to-prod.yml
- .github/workflows/push-to-testnet.yml
- docker-compose.yml
**Why**
- revert privileged containers
- add rockpi builds
- make actions easier to read and maintain using strategy matrix in builds
- sx1302 fixes
**How**
- revert privileged containers based on discussion in #253
- add rockpi builds to testnet and production actions using build matrix
- with rockpi versions, change the i2c bus to i2c-7 in docker-compose
- remove hard coded balena cli version and change to env variable
- bump pktfwd to bring in sx1302 fixes
**References**
Relates-to: #253 
Relates-to: https://github.com/NebraLtd/hm-diag/issues/237
Relates-to: https://github.com/NebraLtd/hm-pyhelper/pull/68
Relates-to: https://github.com/NebraLtd/hm-pktfwd/pull/74
Relates-to: https://github.com/NebraLtd/hm-pktfwd/pull/72
Relates-to: https://github.com/NebraLtd/hm-pktfwd/issues/70
> fix: revert privileged containers and add rockpi builds

- .github/workflows/push-to-prod.yml
- .github/workflows/push-to-testnet.yml
**Why**
Allow some jobs to build even if some fail
**How**
add fail fast false
**References**
https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast
> fix: add fail fast false to matrix workflows

- docker-compose.yml
**Why**
As a diagnostics user, I should be able to clearly differentiate miner errors from Helium API errors so that I have a better sense of what is going wrong.
**How**
Sync Percentage: Add Miner RPC Unavailable
Sync Percentage: Rename Helium API Not Available to Helium API Unavailable
Height Status: Rename Not Available to Miner RPC Unavailable
Height Status: Add Helium API Unavailable.
**References**
https://github.com/NebraLtd/hm-diag/issues/235
> fix: display Miner RPC/Helium API availability correctly

- docker-compose.yml
**Issue**
Fixes the issue where `provision_key` was never getting called.
- Link: https://github.com/NebraLtd/hm-diag/issues/264
> Hotfixing hm-diag#264 and including the new diagnostics hash

- .github/workflows/push-to-prod-draft.yml
- .github/workflows/push-to-testnet-draft.yml
- README.md
**Issue**
- Link: #293
- Summary: draft builds allow us sometimes to push through failed builds when balena having issues.
**How**
Add new manually triggerable action to allow us to push draft builds to balena and then manually finalise them from balenaCloud
**References**
Relates-to: #293
**Checklist**
> feat: add manual draft balena deploy action

- .github/workflows/push-to-prod-draft.yml
- .github/workflows/push-to-prod.yml
**Issue**
- Link: n/a
- Summary: balena builds failing regularly
**How**
Add random sleep period to work around balena API issues
**References**
Related to #293 
**Checklist**
> fix: add random sleep period

- .github/workflows/push-to-prod-draft.yml
- .github/workflows/push-to-prod.yml
- .github/workflows/push-to-testnet-draft.yml
- .github/workflows/push-to-testnet.yml
**Issue**
- Link: #293 
- Summary: balena deploy is unreliable from github actions
**How**
- add multiple balena API tokens to avoid (or at least reduce the impact of) rate limiting
- add random sleep to testnet pushes
**References**
Relates-to: #293
Relates-to: #299
Relates-to: #300
**Checklist**
> fix: add multiple API tokens for balena

- docker-compose.yml
**Issue**
- Link: https://github.com/NebraLtd/hm-diag/issues/252
- Summary: initFile was using out-of-date logic for BT/LTE detection. Diagnostics page (/json endpoint) was using updated logic, but manufacturing (/initFile.txt endpoint) thought BT was failing on ROCK Pis.
**How**
Copy /json logic to /initFile
**References**
- Related to: https://github.com/NebraLtd/hm-diag/pull/272
- Related to: https://github.com/NebraLtd/hm-config/issues/156
**Checklist**
> release(testnet): initFile uses new BT/LTE logic

- docker-compose.yml
**Issue**
- Link: https://github.com/NebraLtd/hm-diag/issues/252
- Summary: initFile was using out-of-date logic for BT/LTE detection. Diagnostics page (/json endpoint) was using updated logic, but manufacturing (/initFile.txt endpoint) thought BT was failing on ROCK Pis.
**How**
Copy /json logic to /initFile
**References**
- Closes: https://github.com/NebraLtd/hm-diag/issues/252
- Related to: https://github.com/NebraLtd/hm-diag/pull/272
- Related to: https://github.com/NebraLtd/hm-config/issues/156
**Checklist**
> release(prod): initFile uses new BT/LTE logic

- docker-compose.yml
**Issue**
- Link: N/A
- Summary: i2c ECC bus missing from hardware details
**How**
Bump diag container
Also adds firmware version to number container so it restarts on every new release.
**References**
Relates to https://github.com/NebraLtd/hm-diag/pull/277
Relates to https://github.com/NebraLtd/hm-pyhelper/pull/84
Related to https://github.com/NebraLtd/hm-config/issues/162
**Checklist**
> feat: bump diag to bring in hm-pyhelper updates

- docker-compose.yml
**Issue**
- Link: https://github.com/NebraLtd/hm-config/issues/162#issuecomment-1001712914
- Summary: adding firmware version to every container forces them to restart every time we push an update
**How**
Adds firmware version to every container so that all updates restart all containers.
**References**
Ref https://github.com/NebraLtd/hm-config/issues/162#issuecomment-1001712914
**Checklist**
> feat: adds firmware version to every container

- docker-compose.yml
**Issue**
- Link: https://github.com/NebraLtd/hm-diag/commit/ccaa8e4c57d6b6681efc21f90c7747d6988ab795
- Summary: balena doesn't fully support health check right now so it's redundant
**How**
bump diagnostics container version
**References**
https://github.com/NebraLtd/hm-diag/commit/ccaa8e4c57d6b6681efc21f90c7747d6988ab795
**Checklist**
> bump diagnostics version

- templates/docker-compose.template
**Issue**
- Link: #343 
- Summary: Diagnostics container missing /proc/device-tree file structure resulting in diagnostics page to not load
**How**
Jinja2 template was missing ```privileged: true``` to allow the container to access system level files, this was added to the template
Closes: #343
> Added privileged: true to diag container

- README.md
**Issue**
- Link: https://github.com/NebraLtd/helium-miner-software/pull/272
- Summary: Switched to generate a docker-compose.yml file based on a jinja2 template with a settings.ini file
**How**
Added readme steps for generating the docker-compose.yml file
Closes: #340
> Update readme to include docker-compose generation steps

- balena/balena.yml.og
**Issue**
- Link: #397 
- Summary: Helium OG miner can be raspberry pi 3
**How**
As per #397 some original helium hotspots use raspberry pi 3 so this PR adds ability to add a Pi3-64bit on the balena openfleet
**References**
#397 
**Checklist**
> feat: bump OG balena.yml to add raspberrypi3-64

- templates/docker-compose.template
**[Issue](https://github.com/NebraLtd/helium-miner-software/issues/427)**
- Link: https://github.com/NebraLtd/helium-miner-software/issues/427
- Summary: gateway-rs listens only on local host. Only way to make diag work at this stage is to use host networking.
**How**
- helium-miner and diagnostics use host networking
**References**
**Checklist**
> fix: Add host networking to hm-miner to access grpc api #427

- templates/docker-compose.template
**Issue**
- Link: https://github.com/NebraLtd/hm-diag/issues/352
- Summary:
There are many Sentry issues related with "gateway_mfr exited with a non-zero status" in `hm-diag`.
This is most likely happening if not all services get restarted when we release a new version to the Balena fleets.
As a convention, we update the `FIRMWARE_VERSION` in the `settings.ini` in the every version update so that all services restart, but if we forget to update `FIRMWARE_VERSION`, then it is the case that only some services will restart.
It would be safer and better solution to add `FIRMWARE_SHORT_HASH` to the environment variable of all the services since its value is generated automatically on every release.
**How**
Add `FIRMWARE_SHORT_HASH` environment variable to `packet-forwarder` and `helium-miner` …
> Add Github short hash to all services

- .github/workflows/push-to-prod-draft.yml
- .github/workflows/push-to-prod.yml
- .github/workflows/push-to-testnet-draft.yml
- .github/workflows/push-to-testnet.yml
latest balena-cli removed --logs option (now defaults to having logs and turn off with --nologs)
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> fix: latest balena-cli removed --logs option

- .github/workflows/linter.yml
- .github/workflows/push-to-prod-draft.yml
- .github/workflows/push-to-prod.yml
- .github/workflows/push-to-testnet-draft.yml
- .github/workflows/push-to-testnet.yml
- .github/workflows/python-tests.yml
- .github/workflows/security-audit.yml
- .github/workflows/update-miner.yml
- .github/workflows/update-production.yml
- balena/workflows/build-open-fleet.yml
- balena/workflows/update-files.yml
bump checkout to v3 for all actions (see https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/ for info)
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> fix: bump checkout to v3 for all actions

- settings.ini
It seems that this modem info was accidentally duplicated here at some point. It is only needed in the Quectel modem part
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> fix: remove duplicate modem info

- gen_docker_compose.py
* generate short hash
**[Issue](https://github.com/NebraLtd/helium-miner-software/issues/651)**
- Link:https://github.com/NebraLtd/helium-miner-software/issues/651
- Summary:
**How**
**References**
**Checklist**
> fix: try to generate short hash if not inherited #651

- balena/workflows/build-open-fleet.yml
${{ github.repository }} gives full nebraltd/helium-nebra-indoor2 repository name.
${{ github.event.repository.name }} only gives helium-nebra-indoor2 without the nebraltd part
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> fix: full repo slug

- balena/workflows/build-open-fleet.yml
${{ github.repository }} gives full nebraltd/helium-nebra-indoor2 repository name.
${{ github.event.repository.name }} only gives helium-nebra-indoor2 without the nebraltd part
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> fix: full repo slug (#696)

- .github/workflows/openfleet-file-update.yml
- balena/workflows/build-open-fleet.yml
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> Merge to prod
